### PR TITLE
QCOSS-108: CiviCRM Contribution processor

### PR DESCRIPTION
**Pull request by agilewarealok**
Created a CiviCRM Contribution processor, which has following fields to configure.

**Required Fields**

- Financial Type
- Currency
- Amount Field

**Other Fields**

- Source Field (If not selected, we set the form name as a source)
- Transaction ID

### CODE REVIEW

**Comment by mecachisenros** [comment]
@agilewarealok thank you for this, I'll review it and test it.

**Comment by agilewarealok** [comment]
Thank you @mecachisenros , Appreciate it.

**Comment by agilewarealok** [comment]
@mecachisenros We've updated the PR with required changes. Please review.

**Comment by mecachisenros** [comment]
@agilewarealok many thanks for this, reviewed and merged.

**Comment by agilewarealok** [comment]
@mecachisenros  Thank you for merging :)

**Pull request merged**
