### PR TITLE
added double optin support for group

### PR DESCRIPTION
**Pull request by kurund**
# Please make all Pull Requests against the dev branch 

Overview
----------------------------------------
_Add a configurable option for enabling double opt-in while adding contact to the group _

Before
----------------------------------------
_Currently contact are directly added to the group. Double opt-in is needed in case of mailing sign up etc._

After
----------------------------------------
_ If double opt-in is enabled then contact needs to verify the email sent and then the contact is added to the group_

Technical Details
----------------------------------------
_PR is self explanatory_

Comments
----------------------------------------
_Thank you for the wonderful plugin_

### CODE REVIEW

**Comment by kcristiano** [comment]
@kurund Can you rebase against dev branch?   All new commits should target the dev branch as that is the most up to date.

**Comment by kcristiano** [comment]
Can you also leave the code style as is and not convert to Drupal stye?

**Comment by kurund** [comment]
@kcristiano Thank you, will submit separate PR later in the week.

**Comment by kurund** [comment]
Closing this in favor of https://github.com/mecachisenros/cf-civicrm/pull/199

**Pull request closed without merging**
