### PR TITLE
Price Field has insufficient decimal precision

### PR DESCRIPTION
**Pull request by jusfreeman**
When using the "Price Field" options to auto populate e.g. a Radio field with price options, they are automatically rounded to two decimal places.

This creates problems with tax inclusive price values (eg. GST 10%) due to rounding.

For example, it is impossible to have an option with a price of $60 because $54.54 + 5.454 = 59.994 ≈ $59.99 and $54.55 + 5.455 = 60.005 ≈ $60.01
Therefore, higher precision is required, e.g.: 54.545 + 5.4545 = 59.9995 ≈ $60.00

We have also seen this problem before in Core CiviCRM, which was eventually solved by introducing higher precision price field values.

This PR adds higher precision decimal places.

Agileware Ref: CFC-12

### CODE REVIEW

**Comment by agileware-fj** [comment]
Hi @mecachisenros – just wondering if you'd had a chance to look at this yet?  We've got someone jumping up and down about how all their $60 memberships are one cent out.

**Comment by mecachisenros** [comment]
@agileware-fj sorry for the radio silence.

This is not needed anymore as there's been work in this regard in the [dev](https://github.com/mecachisenros/caldera-forms-civicrm/tree/dev) branch which is close to be merged to master.

Price fields are not rounded anymore, and left _as they come_ from Civi (precision of 9 I believe), and all displayed prices are formatted [Civi's way](https://github.com/mecachisenros/caldera-forms-civicrm/tree/tax-fixes).

I've created a [tax-fixes](https://github.com/mecachisenros/caldera-forms-civicrm/tree/tax-fixes) branch which includes the last bits 0a91c5ab7d992fe5d5f1787c8312b13f5a1fecef to get this done, I'll appreciate if you can test and confirm that is fixed.

On another note this is somehow related to #87 all explain why in the issue.

**Comment by agileware-fj** [comment]
@mecachisenros Thanks for posting the update.

The output on the form appears to be fine now, total field if included and using money format shows correct value (without money format it shows all the decimal places), but it gives "Line item total doesn't match with total amount." error.

But it works if I comment out the line referenced in #87

**Comment by mecachisenros** [comment]
@agileware-fj as per my comment on #87 I'll close this.

**Pull request closed without merging**
